# Generated by Django 2.0.1 on 2018-02-16 12:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCourses',
            fields=[
                ('ufid', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_id', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('u_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(0, 'Admin'), (1, 'Faculty'), (2, 'Student')])),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('ucid', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_id', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete='cascade', to='User.User')),
            ],
        ),
        migrations.AddField(
            model_name='facultycourses',
            name='user',
            field=models.ForeignKey(on_delete='cascade', to='User.User'),
        ),
    ]
